#!/usr/bin/env python

import sys

from rqt_robin_gcs.robin_gcs import RobinGCS
from rqt_gui.main import Main

plugin = 'rqt_robin_gcs'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
